# Generated by Django 3.0.5 on 2020-04-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postcomment_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='date_posted',
            new_name='date_comment',
        ),
    ]
