# Generated by Django 3.0.5 on 2020-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200416_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='/home/anant/PycharmProjects/Django_try/Django/post/static/post/images/user.jpg', max_length=200, upload_to='postimages/'),
        ),
    ]
