# Generated by Django 3.0.5 on 2020-04-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='Django/avatar.png', max_length=200, upload_to='postimages/'),
        ),
    ]
